# Generated by Django 2.2.7 on 2019-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mguser',
            name='username',
            field=models.CharField(max_length=128, verbose_name='사용자명'),
        ),
    ]
