# Generated by Django 2.2.7 on 2019-12-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mguser', '0002_auto_20191212_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mguser',
            options={'verbose_name': 'mg 사용자', 'verbose_name_plural': 'mg 사용자'},
        ),
        migrations.AddField(
            model_name='mguser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
